baseurl = "/"
Title = "Ein Blog"
languageCode = "de"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Jonah Polack"
theme = "hugo_theme_pickles"

DefaultContentLanguage = "de"

[languages]
  [languages.de]
    languageName = "Deutsch"

[params]
  sortByWeight="desc"
  custom_css = ["/css/custom.css"]
#   paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "jpolack"
  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-134605504-2"
  author = "Jonah Polack"
  avatar = "https://avatars1.githubusercontent.com/u/13745423?s=460&v=4"
  contact = "https://jonahpolack.de"
  bio = "aus Köln und fragt gerne \"Warum?\""
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Es wird das, was es wird"
  favicon = "/path/to/favicon"

# [[menu.main]]
#     name = "Blog"
#     url = "/"
#     weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2

# [[menu.main]]
#     identifier = "theme"
#     name = "/theme"
#     weight = 3

# [[menu.main]]
#     parent = "theme"
#     name = "creating-a-new-theme"
#     url = "/posts/creating-a-new-theme"
#     weight = 1

# [[menu.main]]
#     parent = "theme"
#     name = "migrate-from-jekyll"
#     url = "/posts/migrate-from-jekyll"
#     weight = 2

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
